spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      authentication-database: "admin"
  jackson:
    default-property-inclusion: NON_NULL
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  tomcat:
    uri-encoding: "UTF-8"